on:
  workflow_dispatch:

jobs:
  build-binary:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - run: echo hello
